name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/configure-pages@v5

      - uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: experimental-features = nix-command flakes

      - name: Get pnpm store path
        id: get-pnpm-store-path
        run: nix develop -c bash -c 'echo STORE_PATH=$(pnpm store path --silent) | tee -a $GITHUB_OUTPUT'

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-pnpm-store-path.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-store-

      - name: Install dependencies
        run: nix develop -c pnpm install --frozen-lockfile

      - name: Build
        run: nix develop -c pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
